export const ranks: number[] = new Array(8).fill(0).map((_rank, i) => i + 1);
export const files: number[] = new Array(8).fill(0).map((_file, i) => i + 1);
export const WHITE = "w";
export const BLACK = "b";
export const PENDING = "pending";
export const RUNNING = "running";
export const FINISHED = "finished";
export const UNFINISHED = "unfinished";
// export const ranksArr: number[] = new Array(8).fill(0).map((_rank, i) => i + 1);
export const filesArr: string[] = "abcdefgh".split("");
